# Generated by Django 5.2 on 2025-04-15 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0002_remove_question_exam_board_question_exam_boards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='mcq.topic')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='questions', to='mcq.keyword'),
        ),
    ]
