# Generated by Django 5.2 on 2025-04-15 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0003_keyword_question_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
