# Generated by Django 5.2 on 2025-04-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
