# Generated by Django 5.2 on 2025-04-20 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0009_profile_chain_length_profile_last_chain_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtopics', to='mcq.topic')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'topic')},
            },
        ),
    ]
