# Generated by Django 5.2 on 2025-04-20 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0010_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mcq.subtopic'),
        ),
    ]
