# Generated by Django 5.2 on 2025-04-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0011_question_subtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
