# Generated by Django 5.2 on 2025-04-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0012_question_flagged'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chain_length',
            field=models.IntegerField(default=1),
        ),
    ]
