# Generated by Django 5.2 on 2025-04-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0013_alter_profile_chain_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('hardcore', 'Hardcore'), ('exam', 'Exam')], default='medium', max_length=10),
        ),
        migrations.CreateModel(
            name='Quanta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('visibility', models.CharField(choices=[('creator_only', 'Only Creator Can See Names'), ('all_members', 'All Members Can See Names'), ('anonymous', 'All Anonymous')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invite_code', models.CharField(max_length=12, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quanta', to='mcq.profile')),
            ],
        ),
        migrations.CreateModel(
            name='QuantaMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quanta_memberships', to='mcq.profile')),
                ('quanta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='mcq.quanta')),
            ],
            options={
                'unique_together': {('quanta', 'profile')},
            },
        ),
    ]
