# Generated by Django 5.2 on 2025-05-01 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0015_profile_default_num_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_simulated',
            field=models.BooleanField(default=False),
        ),
    ]
