# Generated by Django 5.2 on 2025-05-01 09:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0016_profile_is_simulated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='date_taken',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
