# Generated by Django 5.2 on 2025-05-02 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0018_profile_accuracy_mean_profile_accuracy_stddev'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='excluded_subtopics',
            field=models.ManyToManyField(blank=True, to='mcq.subtopic'),
        ),
    ]
