# Generated by Django 5.2 on 2025-05-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0019_profile_excluded_subtopics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='excluded_exam_boards',
            field=models.ManyToManyField(blank=True, to='mcq.examboard'),
        ),
    ]
