# Generated by Django 5.2 on 2025-05-03 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq', '0020_profile_excluded_exam_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='excluded_difficulties',
            field=models.JSONField(default=list),
        ),
    ]
